/* =========================================================
   DICTIONARY — Khmer (km) and English (en)
   ========================================================= */
const DICT = {
  en: {
    // tabs
    tabHome: 'Home', tabBrowse: 'Browse', tabBasket: 'Basket', tabOrders: 'Orders', tabAccount: 'Account',
    back: 'Back', close: 'Close', ok: 'OK', goBack: 'Go back', save: 'Save', saved: 'Saved ✓', submit: 'Submit', edit: 'Edit', change: 'Change', remove: 'Remove', undo: 'Undo', clear: 'Clear', optional: 'optional', retry: 'Retry', search: 'Search', add: 'Add', on: 'On', off: 'Off', default: 'Default',
    today: 'Today', tomorrow: 'Tomorrow', yesterday: 'Yesterday',
    // login
    loginTitle: 'HarvestFlow for Restaurants', loginSub: 'Fresh vegetables straight from Battambang cooperatives',
    phone: 'Phone number', code: '4-digit code', login: 'Log in',
    errPhone: 'This phone number is not registered as a restaurant.', errCode: 'Wrong code. Please try again.',
    sellerTitle: 'This account is for cooperatives', sellerMsg: 'Please use the HarvestFlow Seller app.',
    openSellerApp: 'Open the Seller app', liveTag: 'Live', coopAnswered: 'The cooperative already answered this order — it can no longer be cancelled.',
    demoAccounts: 'Demo accounts (tap to fill)', demoBuyer: 'Restaurant', demoSeller: 'Cooperative', demoUnverified: 'Not verified yet',
    sessionExpired: 'Your session expired. Please log in again — we will take you back where you were.',
    welcomeBack: 'Welcome, The Lab ✓',
    verifyTitle: 'Your restaurant is being verified', verifySub: 'You can browse the market now. Ordering opens once HarvestFlow confirms your restaurant (usually within 1 working day).',
    browseMarket: 'Browse the market', verifyBanner: 'Your restaurant is being verified. You can browse, but ordering is not open yet.',
    // home
    searchPh: 'Search fresh vegetables…', categories: 'Categories',
    marketBanner: "Today's Market Price Index", marketBannerSub: '{p} is {pct}% cheaper than the market on HarvestFlow',
    limitedBatches: 'Limited Batches & Surplus', viewAll: 'View all', freshDeals: 'Fresh Deals', freshDealsSub: "Good produce. Special prices. Use it while it's fresh.",
    availableToday: 'Available Today', recentlyOrdered: 'Recently Ordered', noRecent: 'Nothing ordered yet', noDeals: 'No deals right now',
    lastOrdered: 'last ordered', off: 'OFF', leftShort: '{n} kg left',
    // search
    recentSearches: 'Recent searches', noRecentSearch: 'No recent searches', popular: 'Popular today', typeSomething: 'Type a vegetable name',
    shopsN: '{n} shops', from: 'from', shopsFound: '{n} shops found',
    noShopHas: "No shop has '{q}' today", noShopHasSub: 'Try another name, or browse all vegetables.', browseAll: 'Browse all vegetables',
    cheapest: 'Cheapest',
    youSearched: 'You searched', cooperative: 'Cooperative', reviews: 'reviews', since: 'Since', itsVegetables: 'Vegetables from this shop',
    contactCoop: 'Contact cooperative', contactCoopToast: 'Calling the cooperative… (demo)',
    // browse
    browseTitle: 'Browse', browsePh: 'Search inside Browse…', lowestFirst: 'Lowest price first', nListings: '{n} listings', noBrowse: 'Nothing here', showAll: 'Show all',
    by: 'by', grade: 'Grade', kgLeft: '{n} kg left', kgLeftCaps: '{n} KG left', soldOut: 'Sold out', otherShops: 'Other shops ({n})',
    // deals
    flashBatches: 'FLASH BATCHES', allDeals: 'All Deals', useSoon: 'Use Soon', surplus: 'Surplus Harvest', shortestShelf: 'Shortest shelf life', biggestDiscount: 'Biggest discount',
    dealsRule: 'Only deals still fresh on delivery day', harvested: 'Harvested', useBy: 'Suggested use by', estDelivery: 'Est. delivery', nextBatch: 'Next batch arriving', addToCart: 'Add to Cart',
    deal: 'Deal', lineTotal: 'Line total',
    // product
    stockLeft: 'Stock left', minOrder: 'Minimum order', freshUntil: 'Fresh until', deliveryPromise: 'Delivery', storageTemp: 'Storage temp.', certificate: 'Certificate',
    quantity: 'Quantity', qtyHint: 'Min {min} kg · max {max} kg', minOrderMsg: 'Minimum order is {n} kg', maxStockMsg: 'Only {n} kg left in stock', belowMinStock: 'Not enough stock for the minimum order',
    limitMax: 'That is all the stock left', limitMin: 'You have reached the minimum order',
    noteToCoop: 'Note to the cooperative', notePh: 'e.g. Please pack herbs separately', estTotal: 'Estimated total',
    addToBasket: 'Add to Basket', buyNow: 'Buy Now', addedMsg: 'Added {n} kg {p} to basket', dealNote: 'Deal · use by {d}',
    // basket
    basket: 'Basket', basketTitle: 'Basket', basketSub: '{n} shops', viewBasket: 'View basket', nItems: '{n} items',
    basketEmpty: 'Your basket is empty', basketEmptySub: 'Add vegetables from any cooperative.', browseVeg: 'Browse vegetables',
    selectAll: 'Select all', shops: 'shops', noteToShop: 'Note to this cooperative', subtotal: 'Subtotal', deliveryFee: 'Delivery fee',
    itemsTotal: 'Items total', deliveryShort: 'delivery', checkoutBtn: 'Checkout · {n} shops · {total}',
    selectOneShop: 'Select at least one shop', removeUnavailable: 'Remove unavailable items first',
    shopBlocked: 'This shop cannot be checked out until the unavailable item is removed.',
    noLongerAvailable: 'No longer available', priceChanged: 'Price changed from {a} to {b}', onlyLeft: 'Only {n} kg left — quantity lowered',
    removedMsg: '{p} removed',
    // checkout
    checkout: 'Checkout', checkoutSub: '{n} shops · one payment', buyNowSub: 'Buy Now · this item only (your basket is untouched)',
    delivery: 'Delivery', recipient: 'Recipient', date: 'Date', timeWindow: 'Time window', address: 'Address',
    yourOrders: 'Your orders', orderXofY: 'Order {x} of {y}', payment: 'Payment', payKhqr: 'Pay with Bakong KHQR', payKhqrSub: 'Scan with any Cambodian banking app',
    payOnce: 'You pay once. Each cooperative gets its own order and receipt.',
    summary: 'Summary', deliveryTotal: 'Delivery', grandTotal: 'Grand total', placeOrder: 'Place Order', checking: 'Checking stock and prices…',
    notVerifiedTitle: 'Not verified yet', notVerifiedBlock: 'Your restaurant is not verified yet, so you cannot place orders.', notVerifiedShort: 'Ordering opens after verification',
    fixFirst: 'Please check the highlighted order. Nothing was charged.',
    probPrice: '{p}: price changed from {a} to {b}. Tap Place Order again to accept.', probStock: '{p}: only {n} kg left.', probUnavailable: '{p} is no longer available.',
    setTo: 'Set to {n} kg', itemRemoved: 'Item removed', nothingToCheckout: 'Nothing to check out',
    validUntil: 'valid until {t}', saveQr: 'Save QR image', useStaticQr: 'QR not working? Use the fixed QR', useAmountQr: 'Use the QR with the amount',
    typeAmount: 'This fixed QR has no amount. Type {a} yourself and write “{r}” in the note.',
    payStep1: 'Open ABA, ACLEDA, Wing or any Bakong app and scan (or upload the saved image).', payStep2: 'Check the amount is {a} and confirm.', payStep3: 'Come back here and tap “I have paid”.',
    scanToPay: 'Scan to pay', scanToPaySub: 'Bakong KHQR · one payment for all shops', ref: 'Reference', iHavePaid: 'I have paid',
    processing: 'Confirming your payment…', dontClose: 'Please keep this screen open',
    paymentFailed: 'Payment failed', paymentFailedSub: 'Nothing was charged. Please try again.', tryAgain: 'Try again', changePayment: 'Change payment',
    onlyKhqr: 'Bakong KHQR is the only payment method for now.',
    // submitted
    orderSent: 'Order sent!', eachCoopConfirms: 'Each cooperative will confirm your order.', paidTotal: 'Paid total', paidVia: 'Paid via Bakong KHQR ✓',
    submittedNote: 'We will notify you when each cooperative accepts.', viewOrders: 'View Orders', continueShopping: 'Continue shopping',
    // orders
    sortBy: 'Sort by', sortRelevance: 'Relevance', sortRelevanceSub: 'Best match first, deals and Grade A higher', sortPriceSub: 'Lowest price per kg first', sortRatingSub: 'Best-rated cooperatives first', sortDiscount: 'Discount', sortDiscountSub: 'Biggest deals first',
    viewShop: 'Shop', alsoFromShop: 'Also from this cooperative', cheapestShop: 'Cheapest cooperative for this search', nVegShops: '{n} vegetables · {s} shops',
    receipt: 'Receipt', items: 'Items', paidWith: 'Paid with', paidOn: 'Paid on', amount: 'Amount', deliveredAt: 'Delivered', viewReceipt: 'View receipt',
    deliveredTitle: 'Delivered', deliveredSub: 'Your order has arrived. The receipt is in History.',
    yourFeedback: 'Your feedback', reported: 'Problem reported', coopWillReply: 'The cooperative will reply within 24 hours.', editRating: 'Edit rating',
    feedback: 'Feedback', reportHint: 'Short quantity, poor quality, wrong item or late', whatHappened: 'What happened?', submitFeedbackReport: 'Send rating & report',
    rateNeed: 'Choose stars, or report a problem with a reason', reportSentToast: 'Report sent to the cooperative ✓',
    sortPrice: 'Price', sortRating: 'Rating',
    goodFor: 'Good for', dishNeeds: 'Needs {n} vegetables from HarvestFlow', dishPick: 'Cheapest in stock today — tap + to add',
    bestGradeA: 'Best with fresh Grade A', gradeBok: 'Grade B and Fresh Deals are fine here', addAllDish: 'Add all to basket',
    dishAdded: 'Added {p} (minimum order) to basket', dishAlready: 'These vegetables are already in your basket',
    ordersTitle: 'Orders', active: 'Active', history: 'History', noActive: 'No active orders', noHistory: 'No past orders yet',
    trackOrder: 'Track Order', viewDetails: 'View details', checkDelivery: 'Check delivery', rate: 'Rate', rated: 'Rated ★', reorder: 'Reorder', deliveryOn: 'Delivery',
    f_pending: 'Pending', f_preparing: 'Preparing', f_ontheway: 'On the way',
    s_pending: 'Pending', s_accepted: 'Accepted', s_preparing: 'Preparing', s_dispatched: 'Dispatched', s_delivered: 'Delivered', s_completed: 'Completed', s_declined: 'Declined', s_cancelled: 'Cancelled', s_expired: 'Expired', s_disputed: 'Disputed',
    refundPending: 'Refund pending', refunded: 'Refunded',
    // details / track
    orderDetails: 'Order details', orderId: 'Order ID', estArrival: 'Est. arrival', timelineTitle: 'Order timeline', adjustedTotal: 'Adjusted total',
    arrivedTitle: 'Your order arrived. Check it now.', arrivedSub: 'Confirm what you received, or report a problem.',
    cancelOrder: 'Cancel order', cancelQ: 'Cancel this order?', cancelSub: 'The cooperative has not accepted it yet. Your payment for this order will be refunded.', yesCancel: 'Yes, cancel', cancelledToast: 'Order cancelled · refund pending',
    findAnother: 'Find another shop', contactSupport: 'Contact support', supportToast: 'HarvestFlow support: 023 900 100 (demo)',
    disputeOpen: 'Problem reported', disputeItems: 'Items',
    tlSubmitted: 'Submitted', tlAccepted: 'Order accepted', tlPreparing: 'Preparing', tlQuality: 'Quality checked', tlDispatched: 'Dispatched', tlTransit: 'In transit', tlDelivered: 'Delivered',
    waiting: 'Waiting…', onTheWay: 'On the way…',
    itemsBought: 'Items bought', item: 'Item', qty: 'Qty', total: 'Total', totalCost: 'Total cost', route: 'Route', to: 'To', deliveryTimeline: 'Delivery timeline',
    driver: 'Driver', plate: 'Plate', driverSoon: 'A driver will be assigned when the order is dispatched.', callDriver: 'Call Driver', callingDriver: 'Calling {n} · {p} (demo)',
    // receive / report / complete
    receiveTitle: 'Check your delivery', receiveIntro: 'Weigh and check each item, then confirm.', expected: 'Expected', received: 'Received', quality: 'Quality', notOk: 'Not OK',
    addPhoto: 'Add photo', photoAdded: 'Photo added', photoDemo: 'Photo attached (demo placeholder)', noteOpt: 'Note (optional)',
    adjustedAmount: 'Adjusted amount', was: 'was', coopReview: 'The cooperative will review the difference.',
    confirmReceipt: 'Confirm receipt', reportProblem: 'Report a problem', completedToast: 'Receipt confirmed ✓',
    whichItems: 'Which items?', reason: 'Reason', photoNote: 'Photo & note', reportNotePh: 'What happened?', submitReport: 'Submit report', reportNeed: 'Pick at least one item and a reason',
    rShort: 'Short quantity', rQuality: 'Poor quality', rWrong: 'Wrong item', rLate: 'Late', rOther: 'Other',
    reportSent: "We've told the cooperative", reportSentSub: 'They will reply within 24 hours. Your order is marked Disputed.', viewOrder: 'View order', backToOrders: 'Back to orders', status: 'Status',
    orderComplete: 'Order complete', orderCompleteSub: 'Thank you! Your receipt is saved in History.', rateCoop: 'Rate this cooperative', viewHistory: 'View Order History',
    comment: 'Comment', commentPh: 'How was the quality and delivery?', thanksRating: 'Thanks for rating ★{n}',
    reorderDone: '{n} item(s) added to basket at today’s prices', reorderSkipped: 'Not available now, skipped: {p}',
    // market
    marketPrices: 'Market Prices', lastUpdated: 'Last updated today, 6:00 AM', product: 'Product', marketPrice: 'Market', hfLowest: 'HarvestFlow',
    cheaperBy: 'cheaper by {n}%', noSaving: 'same as market', marketNote: 'Market wholesale prices are reference prices. Tap a row to see shops.',
    // account
    accountTitle: 'Account', manager: 'Manager', verifiedB2B: 'Verified B2B', beingVerified: 'Being verified',
    deliveryAddress: 'Delivery address', paymentMethod: 'Payment method', pushNotif: 'Push notifications', notifications: 'Notifications', unreadN: '{n} unread',
    language: 'Language', helpCenter: 'Help Center', logout: 'Log out', logoutQ: 'Log out?', logoutSub: 'Your basket will be cleared.',
    notifOnToast: 'Notifications on', notifOffToast: 'Notifications off', defaultSet: 'Default address updated',
    addAddress: 'Add address', editAddress: 'Edit address', addrLabel: 'Name', addrLabelPh: 'e.g. Restaurant, Kitchen', errAddress: 'Please enter the recipient and address',
    markAllRead: 'Mark all read', noNotif: 'No notifications yet',
    errTitle: 'Could not load', errSub: 'Check your connection and try again.',
    faq1q: 'How does one checkout for many shops work?', faq1a: 'You pay once with Bakong KHQR. Each cooperative gets its own order and receipt, and confirms it separately.',
    faq2q: 'When is the delivery fee charged?', faq2a: 'A delivery fee of $3.00 is charged per cooperative in your checkout.',
    faq3q: 'What if a cooperative declines my order?', faq3a: 'That shop’s part is refunded. The status shows “Refund pending” until it is done.',
    faq4q: 'What if the delivery is short or poor quality?', faq4a: 'On “Check delivery”, enter what you received or tap “Report a problem”. The cooperative reviews it within 24 hours.',
    faq5q: 'Can I cancel an order?', faq5a: 'Yes, while it is still Pending (before the cooperative accepts it).',
  },

  km: {
    tabHome: 'ផ្ទាំងដើម', tabBrowse: 'រកមើល', tabBasket: 'កន្ត្រក', tabOrders: 'បញ្ជាទិញ', tabAccount: 'គណនី',
    back: 'ត្រឡប់', close: 'បិទ', ok: 'យល់ព្រម', goBack: 'ត្រឡប់ក្រោយ', save: 'រក្សាទុក', saved: 'បានរក្សាទុក ✓', submit: 'បញ្ជូន', edit: 'កែ', change: 'ប្តូរ', remove: 'ដកចេញ', undo: 'មិនធ្វើវិញ', clear: 'សម្អាត', optional: 'មិនចាំបាច់', retry: 'ព្យាយាមម្តងទៀត', search: 'ស្វែងរក', add: 'បន្ថែម', on: 'បើក', off: 'បិទ', default: 'លំនាំដើម',
    today: 'ថ្ងៃនេះ', tomorrow: 'ថ្ងៃស្អែក', yesterday: 'ម្សិលមិញ',
    loginTitle: 'HarvestFlow សម្រាប់ភោជនីយដ្ឋាន', loginSub: 'បន្លែស្រស់ៗ ផ្ទាល់ពីសហករណ៍ខេត្តបាត់ដំបង',
    phone: 'លេខទូរស័ព្ទ', code: 'លេខកូដ ៤ ខ្ទង់', login: 'ចូល',
    errPhone: 'លេខទូរស័ព្ទនេះមិនទាន់ចុះឈ្មោះជាភោជនីយដ្ឋានទេ។', errCode: 'លេខកូដមិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។',
    sellerTitle: 'គណនីនេះសម្រាប់សហករណ៍', sellerMsg: 'សូមប្រើកម្មវិធី HarvestFlow សម្រាប់អ្នកលក់។',
    openSellerApp: 'បើកកម្មវិធីអ្នកលក់', liveTag: 'ផ្ទាល់', coopAnswered: 'សហករណ៍បានឆ្លើយតបការបញ្ជាទិញនេះរួចហើយ — មិនអាចបោះបង់បានទៀតទេ។',
    demoAccounts: 'គណនីសាកល្បង (ចុចដើម្បីបំពេញ)', demoBuyer: 'ភោជនីយដ្ឋាន', demoSeller: 'សហករណ៍', demoUnverified: 'មិនទាន់ផ្ទៀងផ្ទាត់',
    sessionExpired: 'វគ្គរបស់អ្នកផុតកំណត់។ សូមចូលម្តងទៀត យើងនឹងនាំអ្នកត្រឡប់ទៅកន្លែងដើមវិញ។',
    welcomeBack: 'សូមស្វាគមន៍ The Lab ✓',
    verifyTitle: 'ភោជនីយដ្ឋានរបស់អ្នកកំពុងត្រូវបានផ្ទៀងផ្ទាត់', verifySub: 'អ្នកអាចមើលទីផ្សារបានឥឡូវនេះ។ ការបញ្ជាទិញនឹងបើក បន្ទាប់ពី HarvestFlow បញ្ជាក់ភោជនីយដ្ឋានរបស់អ្នក (ជាធម្មតាក្នុង ១ ថ្ងៃធ្វើការ)។',
    browseMarket: 'មើលទីផ្សារ', verifyBanner: 'ភោជនីយដ្ឋានកំពុងត្រូវបានផ្ទៀងផ្ទាត់។ អ្នកអាចមើលបាន ប៉ុន្តែមិនទាន់អាចបញ្ជាទិញបានទេ។',
    searchPh: 'ស្វែងរកបន្លែស្រស់ៗ (Search fresh vegetables…)', categories: 'ប្រភេទបន្លែ (Categories)',
    marketBanner: 'សន្ទស្សន៍តម្លៃទីផ្សារថ្ងៃនេះ (Market Prices)', marketBannerSub: '{p} ថោកជាងទីផ្សារ {pct}% នៅលើ HarvestFlow',
    limitedBatches: 'បរិមាណមានកំណត់ និងផលលើស', viewAll: 'មើលទាំងអស់', freshDeals: 'Fresh Deals', freshDealsSub: 'ផលល្អ តម្លៃពិសេស។ ប្រើខណៈពេលនៅស្រស់។',
    availableToday: 'បន្លែស្រស់ថ្ងៃនេះ (Available Today)', recentlyOrdered: 'ធ្លាប់កម្ម៉ង់កន្លងមក (Recently Ordered)', noRecent: 'មិនទាន់មានការបញ្ជាទិញ', noDeals: 'មិនមានការបញ្ចុះតម្លៃទេ',
    lastOrdered: 'កម្ម៉ង់ចុងក្រោយ', off: 'OFF', leftShort: 'សល់ {n}kg',
    recentSearches: 'ការស្វែងរកថ្មីៗ', noRecentSearch: 'មិនមានការស្វែងរកថ្មីៗ', popular: 'ពេញនិយមថ្ងៃនេះ', typeSomething: 'សូមវាយឈ្មោះបន្លែ',
    shopsN: '{n} ហាង', from: 'ពី', shopsFound: 'រកឃើញ {n} ហាង',
    noShopHas: "គ្មានហាងណាមាន '{q}' ថ្ងៃនេះទេ", noShopHasSub: 'សាកល្បងឈ្មោះផ្សេង ឬមើលបន្លែទាំងអស់។', browseAll: 'មើលបន្លែទាំងអស់',
    cheapest: 'ថោកបំផុត',
    youSearched: 'អ្នកបានស្វែងរក', cooperative: 'សហករណ៍', reviews: 'មតិ', since: 'តាំងពី', itsVegetables: 'បន្លែពីហាងនេះ',
    contactCoop: 'ទាក់ទងសហករណ៍', contactCoopToast: 'កំពុងហៅទៅសហករណ៍… (សាកល្បង)',
    browseTitle: 'រកមើល (Browse)', browsePh: 'ស្វែងរកក្នុងបញ្ជីនេះ…', lowestFirst: 'តម្លៃទាបមុន', nListings: '{n} មុខ', noBrowse: 'មិនមានទេ', showAll: 'បង្ហាញទាំងអស់',
    by: 'ដោយ', grade: 'Grade', kgLeft: 'សល់ {n} kg', kgLeftCaps: 'សល់ {n} KG', soldOut: 'លក់អស់', otherShops: 'ហាងផ្សេងទៀត ({n})',
    flashBatches: 'FLASH BATCHES', allDeals: 'ទាំងអស់', useSoon: 'ប្រើឆាប់ៗ', surplus: 'ផលលើស', shortestShelf: 'អាយុកាលខ្លីមុន', biggestDiscount: 'បញ្ចុះច្រើនបំផុត',
    dealsRule: 'បង្ហាញតែផលដែលនៅស្រស់ពេលដឹកដល់', harvested: 'ប្រមូលផល', useBy: 'គួរប្រើមុន', estDelivery: 'ដឹកដល់ប្រហែល', nextBatch: 'បាច់បន្ទាប់មកដល់', addToCart: 'ដាក់ក្នុងកន្ត្រក',
    deal: 'បញ្ចុះតម្លៃ', lineTotal: 'សរុប',
    stockLeft: 'ស្តុកនៅសល់', minOrder: 'កម្ម៉ង់តិចបំផុត', freshUntil: 'ស្រស់រហូតដល់', deliveryPromise: 'ការដឹកជញ្ជូន', storageTemp: 'សីតុណ្ហភាពរក្សាទុក', certificate: 'វិញ្ញាបនបត្រ',
    quantity: 'បរិមាណ', qtyHint: 'តិចបំផុត {min} kg · ច្រើនបំផុត {max} kg', minOrderMsg: 'កម្ម៉ង់តិចបំផុត {n} kg', maxStockMsg: 'ស្តុកនៅសល់តែ {n} kg', belowMinStock: 'ស្តុកមិនគ្រប់សម្រាប់កម្ម៉ង់តិចបំផុត',
    limitMax: 'នេះជាស្តុកទាំងអស់ដែលនៅសល់', limitMin: 'អ្នកដល់ចំនួនកម្ម៉ង់តិចបំផុតហើយ',
    noteToCoop: 'កំណត់ចំណាំទៅសហករណ៍', notePh: 'ឧ. សូមវេចខ្ចប់ជីដាច់ដោយឡែក', estTotal: 'តម្លៃសរុបប៉ាន់ស្មាន',
    addToBasket: 'ដាក់ក្នុងកន្ត្រក', buyNow: 'ទិញឥឡូវ', addedMsg: 'បានដាក់ {p} {n} kg ក្នុងកន្ត្រក', dealNote: 'បញ្ចុះតម្លៃ · គួរប្រើមុន {d}',
    basket: 'កន្ត្រក', basketTitle: 'កន្ត្រក (Basket)', basketSub: '{n} ហាង', viewBasket: 'មើលកន្ត្រក', nItems: '{n} មុខ',
    basketEmpty: 'កន្ត្រករបស់អ្នកទទេ', basketEmptySub: 'បន្ថែមបន្លែពីសហករណ៍ណាមួយ។', browseVeg: 'មើលបន្លែ',
    selectAll: 'ជ្រើសទាំងអស់', shops: 'ហាង', noteToShop: 'កំណត់ចំណាំទៅសហករណ៍នេះ', subtotal: 'សរុបរង', deliveryFee: 'សេវាដឹកជញ្ជូន',
    itemsTotal: 'សរុបទំនិញ', deliveryShort: 'ដឹកជញ្ជូន', checkoutBtn: 'ទូទាត់ · {n} ហាង · {total}',
    selectOneShop: 'សូមជ្រើសយ៉ាងហោចណាស់ ១ ហាង', removeUnavailable: 'សូមដកមុខដែលលែងមានចេញសិន',
    shopBlocked: 'ហាងនេះមិនអាចទូទាត់បានទេ រហូតដល់ដកមុខដែលលែងមានចេញ។',
    noLongerAvailable: 'លែងមានលក់', priceChanged: 'តម្លៃបានប្តូរពី {a} ទៅ {b}', onlyLeft: 'សល់តែ {n} kg — បានបន្ថយបរិមាណ',
    removedMsg: 'បានដក {p} ចេញ',
    checkout: 'ទូទាត់ (Checkout)', checkoutSub: '{n} ហាង · បង់ម្តង', buyNowSub: 'ទិញឥឡូវ · តែមុខនេះប៉ុណ្ណោះ (កន្ត្រកមិនប៉ះពាល់)',
    delivery: 'ព័ត៌មានដឹកជញ្ជូន (Delivery)', recipient: 'អ្នកទទួល', date: 'កាលបរិច្ឆេទ', timeWindow: 'ពេលវេលា (Window)', address: 'អាសយដ្ឋាន',
    yourOrders: 'ការបញ្ជាទិញរបស់អ្នក', orderXofY: 'ការបញ្ជាទិញ {x} នៃ {y}', payment: 'វិធីសាស្ត្រទូទាត់ (Payment)', payKhqr: 'ទូទាត់តាម Bakong KHQR', payKhqrSub: 'ស្កេនទូទាត់ងាយស្រួលតាមកម្មវិធីធនាគារ',
    payOnce: 'អ្នកបង់តែម្តង។ សហករណ៍នីមួយៗទទួលបានការបញ្ជាទិញ និងបង្កាន់ដៃផ្ទាល់ខ្លួន។',
    summary: 'សង្ខេប', deliveryTotal: 'សេវាដឹកជញ្ជូនសរុប', grandTotal: 'ការទូទាត់សរុប (Total)', placeOrder: 'បញ្ជាទិញឥឡូវនេះ', checking: 'កំពុងពិនិត្យស្តុក និងតម្លៃ…',
    notVerifiedTitle: 'មិនទាន់ផ្ទៀងផ្ទាត់', notVerifiedBlock: 'ភោជនីយដ្ឋានរបស់អ្នកមិនទាន់ត្រូវបានផ្ទៀងផ្ទាត់ទេ ដូច្នេះមិនអាចបញ្ជាទិញបានទេ។', notVerifiedShort: 'ការបញ្ជាទិញបើកបន្ទាប់ពីផ្ទៀងផ្ទាត់',
    fixFirst: 'សូមពិនិត្យការបញ្ជាទិញដែលបានសម្គាល់។ មិនទាន់កាត់ប្រាក់ទេ។',
    probPrice: '{p}៖ តម្លៃបានប្តូរពី {a} ទៅ {b}។ ចុច «បញ្ជាទិញ» ម្តងទៀតដើម្បីយល់ព្រម។', probStock: '{p}៖ សល់តែ {n} kg។', probUnavailable: '{p} លែងមានលក់ហើយ។',
    setTo: 'កំណត់ជា {n} kg', itemRemoved: 'បានដកចេញ', nothingToCheckout: 'គ្មានអ្វីត្រូវទូទាត់',
    validUntil: 'មានសុពលភាពដល់ {t}', saveQr: 'រក្សាទុករូប QR', useStaticQr: 'QR មិនដំណើរការ? ប្រើ QR ថេរ', useAmountQr: 'ប្រើ QR ដែលមានចំនួនទឹកប្រាក់',
    typeAmount: 'QR ថេរនេះមិនមានចំនួនទឹកប្រាក់ទេ។ សូមវាយ {a} ដោយខ្លួនឯង ហើយសរសេរ «{r}» ក្នុងកំណត់ចំណាំ។',
    payStep1: 'បើកកម្មវិធី ABA, ACLEDA, Wing ឬ Bakong ហើយស្កេន (ឬបញ្ចូលរូបដែលបានរក្សាទុក)។', payStep2: 'ពិនិត្យថាចំនួនទឹកប្រាក់គឺ {a} រួចបញ្ជាក់។', payStep3: 'ត្រឡប់មកវិញ ហើយចុច «ខ្ញុំបានបង់រួចហើយ»។',
    scanToPay: 'ស្កេនដើម្បីបង់', scanToPaySub: 'Bakong KHQR · បង់ម្តងសម្រាប់គ្រប់ហាង', ref: 'លេខយោង', iHavePaid: 'ខ្ញុំបានបង់រួចហើយ',
    processing: 'កំពុងបញ្ជាក់ការទូទាត់…', dontClose: 'សូមកុំបិទអេក្រង់នេះ',
    paymentFailed: 'ការទូទាត់បរាជ័យ', paymentFailedSub: 'មិនទាន់កាត់ប្រាក់ទេ។ សូមព្យាយាមម្តងទៀត។', tryAgain: 'ព្យាយាមម្តងទៀត', changePayment: 'ប្តូរវិធីទូទាត់',
    onlyKhqr: 'បច្ចុប្បន្នមានតែ Bakong KHQR ប៉ុណ្ណោះ។',
    orderSent: 'បានផ្ញើការបញ្ជាទិញ!', eachCoopConfirms: 'សហករណ៍នីមួយៗនឹងបញ្ជាក់ការបញ្ជាទិញរបស់អ្នក។', paidTotal: 'បានបង់សរុប', paidVia: 'បានបង់តាម Bakong KHQR ✓',
    submittedNote: 'យើងនឹងជូនដំណឹង ពេលសហករណ៍នីមួយៗទទួលយក។', viewOrders: 'មើលការបញ្ជាទិញ', continueShopping: 'បន្តទិញ',
    sortBy: 'តម្រៀប', sortRelevance: 'ពាក់ព័ន្ធបំផុត', sortRelevanceSub: 'ត្រូវនឹងការស្វែងរកមុន បញ្ចុះតម្លៃ និង Grade A មុន', sortPriceSub: 'តម្លៃក្នុង ១ គីឡូ ទាបមុន', sortRatingSub: 'សហករណ៍ដែលមានពិន្ទុខ្ពស់មុន', sortDiscount: 'បញ្ចុះតម្លៃ', sortDiscountSub: 'បញ្ចុះតម្លៃច្រើនមុន',
    viewShop: 'ហាង', alsoFromShop: 'បន្លែផ្សេងទៀតពីសហករណ៍នេះ', cheapestShop: 'សហករណ៍ថោកបំផុតសម្រាប់ការស្វែងរកនេះ', nVegShops: 'បន្លែ {n} មុខ · {s} ហាង',
    receipt: 'បង្កាន់ដៃ', items: 'មុខទំនិញ', paidWith: 'បង់តាម', paidOn: 'ថ្ងៃបង់', amount: 'ចំនួនទឹកប្រាក់', deliveredAt: 'បានដឹកដល់', viewReceipt: 'មើលបង្កាន់ដៃ',
    deliveredTitle: 'បានដឹកដល់', deliveredSub: 'ការបញ្ជាទិញបានមកដល់ហើយ។ បង្កាន់ដៃនៅក្នុងប្រវត្តិ។',
    yourFeedback: 'មតិរបស់អ្នក', reported: 'បានរាយការណ៍បញ្ហា', coopWillReply: 'សហករណ៍នឹងឆ្លើយតបក្នុង ២៤ ម៉ោង។', editRating: 'កែការវាយតម្លៃ',
    feedback: 'មតិយោបល់', reportHint: 'បរិមាណខ្វះ គុណភាពមិនល្អ ខុសមុខទំនិញ ឬមកយឺត', whatHappened: 'តើមានអ្វីកើតឡើង?', submitFeedbackReport: 'ផ្ញើការវាយតម្លៃ និងរបាយការណ៍',
    rateNeed: 'ជ្រើសផ្កាយ ឬរាយការណ៍បញ្ហាជាមួយមូលហេតុ', reportSentToast: 'បានផ្ញើរបាយការណ៍ទៅសហករណ៍ ✓',
    sortPrice: 'តម្លៃ', sortRating: 'ពិន្ទុ',
    goodFor: 'ល្អសម្រាប់', dishNeeds: 'ត្រូវការបន្លែ {n} មុខពី HarvestFlow', dishPick: 'ថោកបំផុតដែលមានថ្ងៃនេះ — ចុច + ដើម្បីបន្ថែម',
    bestGradeA: 'ល្អបំផុតជាមួយ Grade A ស្រស់', gradeBok: 'Grade B និងផលបញ្ចុះតម្លៃ ប្រើបាន', addAllDish: 'ដាក់ទាំងអស់ក្នុងកន្ត្រក',
    dishAdded: 'បានដាក់ {p} (កម្ម៉ង់តិចបំផុត) ក្នុងកន្ត្រក', dishAlready: 'បន្លែទាំងនេះមានក្នុងកន្ត្រករួចហើយ',
    ordersTitle: 'ការបញ្ជាទិញ (Orders)', active: 'កំពុងដំណើរការ', history: 'ប្រវត្តិ', noActive: 'មិនមានការបញ្ជាទិញកំពុងដំណើរការ', noHistory: 'មិនទាន់មានប្រវត្តិ',
    trackOrder: 'តាមដានការដឹក', viewDetails: 'មើលលម្អិត', checkDelivery: 'ពិនិត្យទំនិញ', rate: 'វាយតម្លៃ', rated: 'បានវាយតម្លៃ ★', reorder: 'កម្ម៉ង់ម្តងទៀត', deliveryOn: 'ដឹកជញ្ជូន',
    f_pending: 'រង់ចាំ', f_preparing: 'កំពុងរៀបចំ', f_ontheway: 'កំពុងដឹក',
    s_pending: 'រង់ចាំ (Pending)', s_accepted: 'បានទទួល (Accepted)', s_preparing: 'កំពុងរៀបចំ (Preparing)', s_dispatched: 'កំពុងដឹកជញ្ជូន (Dispatched)', s_delivered: 'បានដឹកដល់ (Delivered)', s_completed: 'បានបញ្ចប់ (Completed)', s_declined: 'បានបដិសេធ (Declined)', s_cancelled: 'បានបោះបង់ (Cancelled)', s_expired: 'ផុតកំណត់ (Expired)', s_disputed: 'មានបញ្ហា (Disputed)',
    refundPending: 'ការសងប្រាក់កំពុងដំណើរការ', refunded: 'បានសងប្រាក់វិញ',
    orderDetails: 'ព័ត៌មានលម្អិត', orderId: 'លេខបញ្ជាទិញ / Order ID', estArrival: 'ពេលវេលាមកដល់ប៉ាន់ស្មាន / Est. Arrival', timelineTitle: 'ដំណើរការបញ្ជាទិញ', adjustedTotal: 'សរុបក្រោយកែតម្រូវ',
    arrivedTitle: 'ទំនិញរបស់អ្នកបានមកដល់។ សូមពិនិត្យឥឡូវនេះ។', arrivedSub: 'បញ្ជាក់អ្វីដែលអ្នកបានទទួល ឬរាយការណ៍បញ្ហា។',
    cancelOrder: 'បោះបង់ការបញ្ជាទិញ', cancelQ: 'បោះបង់ការបញ្ជាទិញនេះ?', cancelSub: 'សហករណ៍មិនទាន់ទទួលយកទេ។ ប្រាក់សម្រាប់ការបញ្ជាទិញនេះនឹងត្រូវសងវិញ។', yesCancel: 'បាទ/ចាស បោះបង់', cancelledToast: 'បានបោះបង់ · កំពុងសងប្រាក់',
    findAnother: 'រកហាងផ្សេង', contactSupport: 'ទំនាក់ទំនងគាំទ្រ', supportToast: 'ជំនួយ HarvestFlow៖ 023 900 100 (សាកល្បង)',
    disputeOpen: 'បានរាយការណ៍បញ្ហា', disputeItems: 'មុខទំនិញ',
    tlSubmitted: 'បានផ្ញើការបញ្ជាទិញ (Submitted)', tlAccepted: 'សំណើបញ្ជាទិញត្រូវបានទទួលយក (Order Accepted)', tlPreparing: 'កំពុងរៀបចំ និងវេចខ្ចប់ (Preparing)', tlQuality: 'បានឆ្លងកាត់ការត្រួតពិនិត្យគុណភាព (Quality Checked)', tlDispatched: 'បានចេញដំណើរដឹកជញ្ជូន (Dispatched)', tlTransit: 'កំពុងដឹកតាមផ្លូវ (In Transit)', tlDelivered: 'ដឹកជញ្ជូនដល់កន្លែង (Delivered)',
    waiting: 'រង់ចាំ…', onTheWay: 'កំពុងធ្វើដំណើរ…',
    itemsBought: 'បញ្ជីកសិផលដែលបានទិញ', item: 'មុខទំនិញ (Item)', qty: 'ចំនួន (Qty)', total: 'តម្លៃសរុប (Total)', totalCost: 'ការទូទាត់សរុប (Total Cost)', route: 'សហករណ៍ និងគោលដៅដឹកជញ្ជូន', to: 'ទៅ', deliveryTimeline: 'ដំណើរការដឹកជញ្ជូន (Delivery Timeline)',
    driver: 'អ្នកដឹកជញ្ជូន', plate: 'ស្លាកលេខ', driverSoon: 'អ្នកដឹកនឹងត្រូវបានកំណត់ ពេលការបញ្ជាទិញចេញដំណើរ។', callDriver: 'ទូរស័ព្ទទៅអ្នកដឹក', callingDriver: 'កំពុងហៅ {n} · {p} (សាកល្បង)',
    receiveTitle: 'ពិនិត្យទំនិញដែលបានទទួល', receiveIntro: 'ថ្លឹង និងពិនិត្យមុខនីមួយៗ រួចបញ្ជាក់។', expected: 'រំពឹង', received: 'បានទទួល', quality: 'គុណភាព', notOk: 'មិនល្អ',
    addPhoto: 'ថតរូប', photoAdded: 'បានភ្ជាប់រូប', photoDemo: 'បានភ្ជាប់រូប (សាកល្បង)', noteOpt: 'កំណត់ចំណាំ (មិនចាំបាច់)',
    adjustedAmount: 'ចំនួនទឹកប្រាក់កែតម្រូវ', was: 'មុន', coopReview: 'សហករណ៍នឹងពិនិត្យភាពខុសគ្នានេះ។',
    confirmReceipt: 'បញ្ជាក់ថាបានទទួល', reportProblem: 'រាយការណ៍បញ្ហា', completedToast: 'បានបញ្ជាក់ការទទួល ✓',
    whichItems: 'មុខណាខ្លះ?', reason: 'មូលហេតុ', photoNote: 'រូបថត និងកំណត់ចំណាំ', reportNotePh: 'តើមានអ្វីកើតឡើង?', submitReport: 'បញ្ជូនរបាយការណ៍', reportNeed: 'សូមជ្រើសមុខទំនិញ និងមូលហេតុ',
    rShort: 'បរិមាណខ្វះ', rQuality: 'គុណភាពមិនល្អ', rWrong: 'ខុសមុខទំនិញ', rLate: 'មកយឺត', rOther: 'ផ្សេងៗ',
    reportSent: 'យើងបានប្រាប់សហករណ៍ហើយ', reportSentSub: 'ពួកគេនឹងឆ្លើយតបក្នុង ២៤ ម៉ោង។ ការបញ្ជាទិញត្រូវបានសម្គាល់ថា «មានបញ្ហា»។', viewOrder: 'មើលការបញ្ជាទិញ', backToOrders: 'ត្រឡប់ទៅការបញ្ជាទិញ', status: 'ស្ថានភាព',
    orderComplete: 'ការបញ្ជាទិញបានបញ្ចប់', orderCompleteSub: 'អរគុណ! បង្កាន់ដៃត្រូវបានរក្សាទុកក្នុងប្រវត្តិ។', rateCoop: 'វាយតម្លៃសហករណ៍នេះ', viewHistory: 'មើលប្រវត្តិការបញ្ជាទិញ',
    comment: 'មតិ', commentPh: 'គុណភាព និងការដឹកជញ្ជូនយ៉ាងដូចម្តេច?', thanksRating: 'អរគុណសម្រាប់ការវាយតម្លៃ ★{n}',
    reorderDone: 'បានដាក់ {n} មុខក្នុងកន្ត្រក តាមតម្លៃថ្ងៃនេះ', reorderSkipped: 'មិនមានលក់ឥឡូវ បានរំលង៖ {p}',
    marketPrices: 'តម្លៃទីផ្សារ (Market Prices)', lastUpdated: 'ធ្វើបច្ចុប្បន្នភាព ថ្ងៃនេះ ម៉ោង ៦:០០ ព្រឹក', product: 'មុខទំនិញ', marketPrice: 'ទីផ្សារ', hfLowest: 'HarvestFlow',
    cheaperBy: 'ថោកជាង {n}%', noSaving: 'ដូចទីផ្សារ', marketNote: 'តម្លៃលក់ដុំទីផ្សារ ជាតម្លៃយោង។ ចុចលើជួរដើម្បីមើលហាង។',
    accountTitle: 'គណនី (Account)', manager: 'អ្នកគ្រប់គ្រង', verifiedB2B: 'បានផ្ទៀងផ្ទាត់ B2B', beingVerified: 'កំពុងផ្ទៀងផ្ទាត់',
    deliveryAddress: 'អាសយដ្ឋានដឹកជញ្ជូន', paymentMethod: 'វិធីទូទាត់', pushNotif: 'ការជូនដំណឹង Push', notifications: 'ការជូនដំណឹង', unreadN: '{n} មិនទាន់អាន',
    language: 'ភាសា', helpCenter: 'មជ្ឈមណ្ឌលជំនួយ', logout: 'ចាកចេញ', logoutQ: 'ចាកចេញ?', logoutSub: 'កន្ត្រករបស់អ្នកនឹងត្រូវសម្អាត។',
    notifOnToast: 'បានបើកការជូនដំណឹង', notifOffToast: 'បានបិទការជូនដំណឹង', defaultSet: 'បានប្តូរអាសយដ្ឋានលំនាំដើម',
    addAddress: 'បន្ថែមអាសយដ្ឋាន', editAddress: 'កែអាសយដ្ឋាន', addrLabel: 'ឈ្មោះ', addrLabelPh: 'ឧ. ភោជនីយដ្ឋាន, ផ្ទះបាយ', errAddress: 'សូមបញ្ចូលអ្នកទទួល និងអាសយដ្ឋាន',
    markAllRead: 'អានទាំងអស់', noNotif: 'មិនទាន់មានការជូនដំណឹង',
    errTitle: 'មិនអាចផ្ទុកបាន', errSub: 'សូមពិនិត្យអ៊ីនធឺណិត ហើយព្យាយាមម្តងទៀត។',
    faq1q: 'តើការទូទាត់ម្តងសម្រាប់ហាងច្រើនដំណើរការយ៉ាងដូចម្តេច?', faq1a: 'អ្នកបង់ម្តងតាម Bakong KHQR។ សហករណ៍នីមួយៗទទួលបានការបញ្ជាទិញ និងបង្កាន់ដៃផ្ទាល់ខ្លួន ហើយបញ្ជាក់ដាច់ដោយឡែក។',
    faq2q: 'តើសេវាដឹកជញ្ជូនគិតយ៉ាងដូចម្តេច?', faq2a: 'សេវាដឹកជញ្ជូន $3.00 សម្រាប់សហករណ៍នីមួយៗក្នុងការទូទាត់។',
    faq3q: 'ចុះបើសហករណ៍បដិសេធ?', faq3a: 'ផ្នែកនៃហាងនោះត្រូវសងប្រាក់វិញ។ ស្ថានភាពបង្ហាញ «ការសងប្រាក់កំពុងដំណើរការ» រហូតដល់រួចរាល់។',
    faq4q: 'ចុះបើទំនិញខ្វះ ឬគុណភាពមិនល្អ?', faq4a: 'នៅពេល «ពិនិត្យទំនិញ» បញ្ចូលអ្វីដែលបានទទួល ឬចុច «រាយការណ៍បញ្ហា»។ សហករណ៍នឹងពិនិត្យក្នុង ២៤ ម៉ោង។',
    faq5q: 'តើខ្ញុំអាចបោះបង់ការបញ្ជាទិញបានទេ?', faq5a: 'បាន ពេលវានៅជា «រង់ចាំ» (មុនសហករណ៍ទទួលយក)។',
  },
};
